### ISSUE TITLE
关于初始数据库示例mysql.sql文件？

### ISSUE THREAD

**Issue by fanys0806** [flute/survey#1]
在安装过程中遇到数据库初始化的问题，想知道是否能提供一个mysql.sql示例作为示范导入数据库，帮助完成数据库的初始化。非常感谢你的指导与帮助^-^！

**Comment by flute** [comment]
这是sql结构，但是登陆的部分你需要自己修改下，以及用户信息，现在的登陆是sso单点登录。

报错信息在logs文件夹中可以看到，方便调试修改。


开 2017年6月21日 在 上午10:49:29, Fan Yingshuang (notifications@github.com) 写到:

在安装过程中遇到数据库初始化的问题，想知道是否能提供一个mysql.sql示例作为示范导入数据库，帮助完成数据库的初始化。非常感谢你的指导与帮助^-^！

**Comment by fanys0806** [comment]
非常感谢，因为是新手所以不知道从哪里开始o(>-<)o。您所说的sql结构，尤其是表结构应该在哪里查看？还是说有可以自动建表的方法...谢谢前辈的指点！

**Comment by flute** [comment]
发给你的这个就是从mysql导出来的表结构，注释什么的都有，你可以打开看。
这个也文件也是建库脚本，用连接数据库的工具连接后，导入这个文件就可以创建成功。具体的步骤你可以百度/google搜索下。


开 2017年6月21日 在 下午1:59:52, Fan Yingshuang (notifications@github.com) 写到:

非常感谢，因为是新手所以不知道从哪里开始o(>-<)o。您所说的sql结构，尤其是表结构应该在哪里查看？还是说有可以自动建表的方法...谢谢前辈的指点！

**Comment by fanys0806** [comment]
对不起可能是我的网络连接有问题，反复看了前后两个回复，但是没有找到您说的文件...我的个人邮箱是fanys0806@gmail.com；可以麻烦您发送到邮箱吗？实在麻烦您啦o(>3<)o!

**Comment by fanys0806** [comment]
已经收到邮件，非常感谢前辈的指点>~<！
